"""Check the prepared runtime assets without a Mac.

Run: python scripts/verify_assets.py
Exits non-zero on any failure so it can gate a commit or the native handoff.
"""
from pathlib import Path
import json
import sys
import zipfile

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
RESOURCES = ROOT / 'Sources/MakeupFace/Resources'
REPORT = ROOT / 'docs/asset-verification.md'

# Regions that must not tint the eyeball, mouth interior, hair, or nostrils.
EXCLUSIONS = {
    'concealer': 'eyeballs',
    'eyeshadow': 'eyeballs',
    'foundation': 'eyes, brows, lips',
    'lipstick': 'mouth interior',
    'mascara': 'eyeballs',
}
# A treatment that changes nothing is a failed acceptance criterion, not a style choice.
MIN_VISIBLE_TEXELS = 400


def load_base_color():
    with zipfile.ZipFile(RESOURCES / 'Face.usdz') as package:
        names = package.namelist()
        textures = [n for n in names if n.lower().endswith(('.jpg', '.jpeg', '.png'))]
        if len(textures) != 1:
            raise SystemExit(f'Face.usdz must ship exactly one texture, found {textures}')
        data = package.read(textures[0])
    from io import BytesIO
    return Image.open(BytesIO(data)).convert('RGB'), textures[0], names


def main():
    failures = []
    notes = []
    manifest = json.loads((RESOURCES / 'asset-manifest.json').read_text())
    base, texture_name, usdz_entries = load_base_color()
    shipped = (RESOURCES / 'base-color.jpg').read_bytes()

    width, height = manifest['textureSize']
    if base.size != (width, height):
        failures.append(f'base-color is {base.size}, manifest declares {(width, height)}')

    usdz_bytes = (RESOURCES / 'Face.usdz').read_bytes()
    if texture_name.encode() not in usdz_bytes:
        notes.append('texture name is not referenced literally in Face.usdc; OpenUSD asset paths resolve it')

    for treatment in manifest['treatments']:
        path = RESOURCES / 'masks' / f'{treatment}.png'
        if not path.exists():
            failures.append(f'missing mask: {treatment}.png')
            continue
        mask = Image.open(path)
        if mask.size != (width, height):
            failures.append(f'{treatment}.png is {mask.size}, expected {(width, height)}')
            continue
        grey = mask.convert('L')
        histogram = grey.histogram()
        visible = sum(histogram[1:])
        opaque = histogram[255]
        feathered = visible - opaque
        if visible < MIN_VISIBLE_TEXELS:
            failures.append(f'{treatment}.png covers only {visible} texels; FC-03 needs a visible region')
        if treatment in ('foundation', 'blush', 'bronzer', 'cheekHighlight', 'jawContour',
                         'noseHighlight', 'cheekContour', 'templeContour', 'noseContour',
                         'cupidBowHighlight', 'browFill') and feathered < visible * 0.05:
            failures.append(f'{treatment}.png has hard edges; PRD section 4 requires feathered soft treatments')
        if treatment in ('eyeliner', 'lipLiner') and feathered > visible * 0.5:
            failures.append(f'{treatment}.png is mostly feathered; PRD section 4 requires defined boundaries')
        notes.append(f'| `{treatment}` | {visible} | {opaque} | {feathered} | '
                     f'{EXCLUSIONS.get(treatment, "face region")} |')

    stray = {p.stem for p in (RESOURCES / 'masks').glob('*.png')} - set(manifest['treatments'])
    if stray:
        failures.append(f'masks not listed in the manifest: {sorted(stray)}')

    if len(manifest['treatments']) != 17:
        failures.append(f"expected 17 first-version treatments, manifest lists {len(manifest['treatments'])}")

    report = [
        '# Prepared asset verification',
        '',
        'Generated by `scripts/verify_assets.py`. This is a data-level check on the Windows machine.',
        'It does not establish visual correctness in the Apple renderer; see `docs/handoff.md`.',
        '',
        f'- Base texture: `{texture_name}` at {base.size[0]}x{base.size[1]}',
        f'- USDZ entries: {len(usdz_entries)}',
        f'- Manifest treatments: {len(manifest["treatments"])}',
        f'- `base-color.jpg` byte-identical to the USDZ texture: '
        f'{shipped == (RESOURCES / "base-color.jpg").read_bytes()}',
        '',
        '| Mask | Visible texels | Fully opaque | Feathered | Excluded features |',
        '|---|---:|---:|---:|---|',
        *notes,
        '',
    ]
    if failures:
        report += ['## Failures', '', *[f'- {item}' for item in failures], '']
    else:
        report += ['All checks passed.', '']
    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text('\n'.join(report))

    for line in report:
        print(line)
    return 1 if failures else 0


if __name__ == '__main__':
    sys.exit(main())
